### ISSUE TITLE
ancient addon - please update

### ISSUE THREAD

**Issue by pawkon** [kodi-game/game.libretro.uae#2]
Could You please update this addon to the version which is in https://github.com/libretro/libretro-uae. This is an ancient version which is unable to run with WHDLoad and hdf files properly. After update it will be possible to use it with most common launcher this days which is IAGL.

**Comment by garbear** [comment]
I update all kodi-game libretro cores every few months, but the march update failed to compile this add-on. I'll post the build failure next time I'm by my build machine

**Comment by pawkon** [comment]
After updating mk files, both game.libretro.uae and libretro.uae, to the newest version from the github I was able to compile newest working version of libretro p-uae. There is no error while compiling and hdf games are loading just fine.  So I think source code of the Libreelec should be updated to provide newer version.

**Comment by garbear** [comment]
I updated the add-on 11 days ago: https://github.com/kodi-game/game.libretro.uae/commit/3fe1701e42d8878fb1b442e791cca0e38377652f

LibreELEC might be using an older version. Can you have them update?

**Comment by pawkon** [comment]
I could try, but it turned out that there is a problem with controllers. I don't know why but my dualshock3 pad and keyboard is not responding in every game. I have to deal with this at first. Maybe You have some experience with this?

**Comment by garbear** [comment]
Input not working is my specialty :) Can you post a link to a debug log?

**Comment by pawkon** [comment]
here it is : https://pastebin.com/6JwnjKnd
I pressed almost every key on keyboard but nothing happens in the game

**Comment by aleksguz** [comment]
@garbear got the same problem with the input...

**Comment by pawkon** [comment]
Hi, any progress on this? Have You found something?

**Comment by garbear** [comment]
Generally my weekends are when I have time for Kodi work, and lately they've been busy. I'll look into this when I get a chance!

**Comment by pawkon** [comment]
Sure, will wait patiently ... with a fingers crossed for Your free time :)

**Comment by aleksguz** [comment]
Thanks in advance!

**Comment by garbear** [comment]
UAE is now updated with the rest of the add-ons. The solution was this patch: https://github.com/kodi-game/game.libretro.uae/blob/master/depends/common/uae/0001-set-core-options-in-retro_set_environment.patch
